<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product-image</name>
   <tag></tag>
   <elementGuidId>66bfa75a-858d-4e3c-b008-a889f0c58a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://cdn-amz.woka.io/images/I/51Nk5SEBARL._SR200,200_.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>396d214b-adb8-43fc-b717-e8d64a8eec7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image</value>
      <webElementGuid>a6792dc8-7820-48c8-9ab8-12be55b7838f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-amz.woka.io/images/I/51Nk5SEBARL._SR200,200_.jpg</value>
      <webElementGuid>90d90d87-29e7-4c56-ba0a-98994ba42737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;category-page&quot;]/div[@class=&quot;category-layout&quot;]/div[@class=&quot;mz-layout&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;mz-layout__inner&quot;]/div[@class=&quot;mz-layout__main-col&quot;]/section[@class=&quot;category-content-section&quot;]/div[@class=&quot;section-body&quot;]/div[@class=&quot;category-product-card-wrap mz-grid mz-gap-8 mz-grid-cols-4 is-loading&quot;]/div[@class=&quot;product-card-col&quot;]/div[@class=&quot;price-product-card&quot;]/a[@class=&quot;product-image-card&quot;]/img[@class=&quot;product-image&quot;]</value>
      <webElementGuid>9f2668ad-a967-4020-ac4a-f0d9f1b6b315</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-amz.woka.io/images/I/51Nk5SEBARL._SR200,200_.jpg')]</value>
      <webElementGuid>e25d1692-56c6-438e-ae93-cea05a67827c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/a/img</value>
      <webElementGuid>b2f09f80-3074-4ee3-ac8b-43f5799b8cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-amz.woka.io/images/I/51Nk5SEBARL._SR200,200_.jpg']</value>
      <webElementGuid>6c97b67a-4a60-4dff-b346-cd44751860f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
