<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hc Cch HcSch khng h tr Bookcare119.000357.000</name>
   <tag></tag>
   <elementGuidId>7049e77b-61d6-449f-9648-b48bcbf03a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.styles__Row-sc-baodwo-0.styles__StyledNormalProduct-sc-baodwo-1.fNFAoO.jjBWEQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div/div[2]/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e64f495-a778-4e7c-8221-a8ac1d10740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__Row-sc-baodwo-0 styles__StyledNormalProduct-sc-baodwo-1 fNFAoO jjBWEQ</value>
      <webElementGuid>4df561e3-9b93-44c3-8644-38d8f6e38013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Học Cách HọcSách không hỗ trợ Bookcare119.000₫357.000₫</value>
      <webElementGuid>fc3136ac-ed1c-4c41-905c-a030312db097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;cart-page&quot;]/main[1]/div[@class=&quot;styles__StyledMainComponent-sc-1mncg38-0 dvFPWG&quot;]/div[@class=&quot;styles__Content-sc-1mncg38-1 kXPYZZ&quot;]/div[@class=&quot;styles__Left-sc-1mncg38-2 negmo&quot;]/div[2]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;styles__StyledSeller-sc-wr0x6x-0 dPgBoJ&quot;]/div[@class=&quot;styles__StyledIntended-sc-wr0x6x-1 gkXJew&quot;]/div[@class=&quot;styles__Row-sc-baodwo-0 styles__StyledNormalProduct-sc-baodwo-1 fNFAoO jjBWEQ&quot;]</value>
      <webElementGuid>6db507e2-bff7-415b-bf11-005e1254055b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>063bbb2d-f70e-4f94-86e6-3e2fb0152782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>935c6d6d-3024-4767-a425-767f44368cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Học Cách HọcSách không hỗ trợ Bookcare119.000₫357.000₫' or . = 'Học Cách HọcSách không hỗ trợ Bookcare119.000₫357.000₫')]</value>
      <webElementGuid>a593f7cc-2c9f-4109-92d8-e271544f98e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
