<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ng nhp</name>
   <tag></tag>
   <elementGuidId>fdf25862-c594-42fa-a12b-81ca2ce15794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.section-body__item-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10f8c3cc-2852-41e1-982a-58f6928437f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-body__item-text</value>
      <webElementGuid>7c1116bb-7106-4f2a-bfea-a69dbf529acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Đăng nhập
              </value>
      <webElementGuid>36589256-f16f-4419-a3a0-206c36c7e3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__user-col&quot;]/a[@class=&quot;section-body__item&quot;]/div[@class=&quot;section-body__item-text&quot;]</value>
      <webElementGuid>f0cad8d9-4d29-4501-8c56-388fc96bd89e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      <webElementGuid>5f5ae4f5-6099-45b3-84e1-64034b57b8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>e32da15b-95ce-4ee1-88d0-37978fe3d0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Đăng nhập
              ' or . = '
                Đăng nhập
              ')]</value>
      <webElementGuid>6508e870-285e-4e63-b787-f6ee3b1e984b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
