<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mz-header-vsearch__keyword-input</name>
   <tag></tag>
   <elementGuidId>0076abb5-a8e9-4f6b-921c-2f30fb79ca50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mz-header-vsearch__keyword-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>808620d4-4e8c-49b5-b17b-9877f4173294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm nội địa, gia dụng, bách hoá, công nghệ, thể thao...</value>
      <webElementGuid>bd54d390-f877-40a8-987e-78502191ec52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f05fb26-2215-4097-a668-15a9a4f325c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75ba29ab-f575-4195-857b-9123dc735c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mz-header-vsearch__keyword-input</value>
      <webElementGuid>0a6c65b2-7b57-4faf-ba9b-63973b7dd03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__search-col&quot;]/div[@class=&quot;search-form&quot;]/div[@class=&quot;mz-header-vsearch is-focus&quot;]/div[@class=&quot;mz-header-vsearch__input-group&quot;]/input[@class=&quot;mz-header-vsearch__keyword-input&quot;]</value>
      <webElementGuid>0962eb7e-fec9-428e-be2f-c34082e52af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>6cf85416-9861-4bab-8992-16aebdffd871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>85df1ac5-cca2-428d-9ce7-e6b8a2db1486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>66b550de-1577-43bf-b8e4-3a5a76aa5351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm sản phẩm nội địa, gia dụng, bách hoá, công nghệ, thể thao...' and @type = 'text']</value>
      <webElementGuid>7d3edef9-7b0e-4000-8f09-0591076e494c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
