<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mz-header-vsearch__keyword-input</name>
   <tag></tag>
   <elementGuidId>41f6cbd5-b290-4006-8766-a8bedb3583b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mz-header-vsearch__keyword-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dbc284c-4039-4b1a-acb9-05549471781c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm nội địa, gia dụng, bách hoá, công nghệ, thể thao...</value>
      <webElementGuid>661362a3-a0d5-44fe-a910-11b254f32a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>306a87a1-f4e6-4d9b-ae55-5f9ad67cc1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a8010ffe-4fa0-405b-856d-7462e84dbcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mz-header-vsearch__keyword-input</value>
      <webElementGuid>0d9e6e1b-245f-41b0-8f2f-99a1a0d6d9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__search-col&quot;]/div[@class=&quot;search-form&quot;]/div[@class=&quot;mz-header-vsearch is-focus&quot;]/div[@class=&quot;mz-header-vsearch__input-group&quot;]/input[@class=&quot;mz-header-vsearch__keyword-input&quot;]</value>
      <webElementGuid>51ff490b-8c84-4e5c-9077-d2ab272ff16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>a144395a-b7b9-49ff-92ef-78d20c529338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>498c0f95-fa11-4b2d-81b5-dbb6c5dd8729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9a9cf20f-ae3c-4971-9d45-bc1aa3a3d960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tìm sản phẩm nội địa, gia dụng, bách hoá, công nghệ, thể thao...' and @type = 'text']</value>
      <webElementGuid>a7681c1e-cf1e-466b-88e0-ddf8bc9c26f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
