<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_submit-btn-bg</name>
   <tag></tag>
   <elementGuidId>58be28a2-3f00-4add-9a50-b6e29d5b48bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='header-section']/div[2]/div/div/div[2]/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.submit-btn-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d2d1d7f4-33b6-4264-8cea-604bd8a9e69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn-label</value>
      <webElementGuid>150ad04a-9668-47d3-80e5-77fb176b8999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__search-col&quot;]/div[@class=&quot;search-form&quot;]/button[@class=&quot;submit-btn&quot;]/span[@class=&quot;submit-btn-label&quot;]</value>
      <webElementGuid>570ef262-37e2-412d-acc2-d85bfbeabbaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[2]/div/button/span[2]</value>
      <webElementGuid>a99c0c3f-ec63-49f4-b2d9-33eaf01641ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>b42d0341-0021-4abb-9515-d2ea46b6f2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[2]/div/button/span</value>
      <webElementGuid>8e15eec1-abf4-4c23-9fe5-17ae198db2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>5d300006-340c-4777-8266-fd6502aea162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
