<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thm vo gi</name>
   <tag></tag>
   <elementGuidId>365a54af-4533-4aa6-829f-2972c69f66fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles__SecondaryButtonStyled-sc-hxh84z-1.jZCrXg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f81fc39-64b5-47e4-832d-32c5dbb1a81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b6f43a5-e2c0-4add-8abf-b5c256782c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-id</name>
      <type>Main</type>
      <value>pdp_add_to_cart_button</value>
      <webElementGuid>1307bd5c-1e3f-4845-88f3-7214ebe27e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__SecondaryButtonStyled-sc-hxh84z-1 jZCrXg</value>
      <webElementGuid>48dc979c-e590-4b6f-ae09-f72452571cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thêm vào giỏ</value>
      <webElementGuid>24901412-0810-40b2-be61-5acb5b5f2089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[1]/div[@class=&quot;ContainerRevamp-sc-1hvvgwz-0 dOGdaN&quot;]/div[@class=&quot;sc-Jgsit bNqXxX&quot;]/div[@class=&quot;sc-igOmtu fyzFIs&quot;]/div[@class=&quot;RightBody__RightStyled-sc-vlexp8-0 grJPUk&quot;]/div[1]/div[@class=&quot;WidgetTitle__WidgetContainerStyled-sc-12sadap-0 bufoOo&quot;]/div[@class=&quot;styles__StyledAddToCart-sc-1pcjtns-0 eEcWHI&quot;]/div[@class=&quot;group-button&quot;]/button[@class=&quot;styles__SecondaryButtonStyled-sc-hxh84z-1 jZCrXg&quot;]</value>
      <webElementGuid>d66c432e-3119-488f-81bd-a9120176f947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d46d0bbf-2dfb-4624-b799-e2903488ece3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div[2]/div/div/div[2]/div[3]/button[2]</value>
      <webElementGuid>0a21e0ab-778a-4ec7-be30-ec5fca1259d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>154ebab6-d59e-45ae-a433-35fe15d92fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Thêm vào giỏ' or . = 'Thêm vào giỏ')]</value>
      <webElementGuid>14ede3cc-17e7-4c51-b870-47d2cbe3b544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
