<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_119.000</name>
   <tag></tag>
   <elementGuidId>71621daf-94a3-45bc-a39a-f6babe80d0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-price__current-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>966aaf53-d127-49b3-87ca-706f443ff308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-price__current-price</value>
      <webElementGuid>59bacf7b-4f90-412f-a0c2-79b6c9d8b19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>119.000₫</value>
      <webElementGuid>6cf6cb10-d943-46e2-88d1-6c769904d38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[1]/div[@class=&quot;ContainerRevamp-sc-1hvvgwz-0 dOGdaN&quot;]/div[@class=&quot;sc-Jgsit bNqXxX&quot;]/div[@class=&quot;sc-igOmtu fyzFIs&quot;]/div[@class=&quot;sc-Jgsit bNqXxX&quot;]/div[@class=&quot;styles__Wrapper-sc-pmgxyr-0 jvWfki&quot;]/div[@class=&quot;styles__StyledProductContent-sc-vbj4qy-0 fegGLL&quot;]/div[@class=&quot;styles__BodyContainerStyled-sc-10qbgzc-0 uPvBM&quot;]/div[@class=&quot;WidgetTitle__WidgetContainerStyled-sc-12sadap-0 bufoOo&quot;]/div[@class=&quot;styles__BodyInfoStyled-sc-smyo6b-3 eDHhpS&quot;]/div[1]/div[2]/div[@class=&quot;style__StyledProductPrice-sc-asj6qq-0 jkiKKI&quot;]/div[@class=&quot;product-price&quot;]/div[@class=&quot;product-price__current-price&quot;]</value>
      <webElementGuid>59a15d78-4cfa-47ff-b071-3e57fb600289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>f1bafdfe-e397-417d-97d4-07d0988bafac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>d6962c8d-ee67-42ea-b628-39db3e860dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '119.000₫' or . = '119.000₫')]</value>
      <webElementGuid>8e7c8a6d-fc83-4755-abbf-0be10b6f70d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
