<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>4c50003c-e486-41ff-8f7a-6a23cd3cd08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-block__form-group__email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-block__form-group__email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ac70482-3e0c-4c59-86cd-7768cf849c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e9d2207a-bf59-483d-b0c3-f71983db3697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-block__form-group__email</value>
      <webElementGuid>f27c7448-3553-4b75-9bc6-83a1fada9028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-form-control</value>
      <webElementGuid>6c449390-3bd3-4b4a-849f-8165fdc2b50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7c9a19e8-ca26-4f9b-9dc0-b3e79ade4deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attributename</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1794ee72-d50f-4fdb-9166-e22027bd300e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email của quý khách</value>
      <webElementGuid>da12ad4f-b06c-4923-a1a1-1c45fff9fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-block__form-group__email&quot;)</value>
      <webElementGuid>97fa3f60-5a98-4a5b-93b2-3230f0fb62b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-block__form-group__email']</value>
      <webElementGuid>81e1d7f4-34ac-4c09-950d-fb9df263d670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-block__login-form']/div/div[2]/div/input</value>
      <webElementGuid>caf59308-6341-4855-8ceb-9f4812d93322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4225190-fc8e-44a5-9234-bacb6d1f1f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'auth-block__form-group__email' and @name = 'email' and @placeholder = 'Địa chỉ email của quý khách']</value>
      <webElementGuid>3e6572f5-1151-4e69-9270-79b6cf30ebf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
