<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>43f209c6-6aa1-4843-b3ee-b40c5a24610f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-block__form-group__email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-block__form-group__email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce65d5fd-0b1e-46a7-84fe-5f9845534cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>65930aae-b7bc-4df3-93ff-60130af32a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-block__form-group__email</value>
      <webElementGuid>3996a0eb-31c1-4120-8d8d-6dede7f31f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-form-control</value>
      <webElementGuid>cc420f0e-a7b8-4004-b2dd-d230b9d8d80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0867eca3-1134-4e7e-8e39-c627a8339e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attributename</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cec90b38-a687-4901-b0fc-7346bdba5d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email của quý khách</value>
      <webElementGuid>e432119e-1def-4b32-8d64-8b3891024df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-block__form-group__email&quot;)</value>
      <webElementGuid>a0cdd155-e691-4b04-9aac-130e2e64f001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-block__form-group__email']</value>
      <webElementGuid>dde7dd28-f815-4d17-aa4b-10a3269781c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-block__login-form']/div/div[2]/div/input</value>
      <webElementGuid>c46ff202-a230-4532-80f9-854518ca9061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b67864d8-1414-4902-b6fd-1cb9338a1c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'auth-block__form-group__email' and @name = 'email' and @placeholder = 'Địa chỉ email của quý khách']</value>
      <webElementGuid>68e2a517-c8b0-416d-b07b-19cd12638c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
