<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xoa</name>
   <tag></tag>
   <elementGuidId>259d6ec3-2f1f-48ff-ba49-2e1009be4635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d3c9daf-a45f-4b75-b3c0-34a4113785f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Xoá sản phẩm</value>
      <webElementGuid>ec43ce21-0c7c-4293-895d-cc35f72e25be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-btn</value>
      <webElementGuid>9fd43b19-6482-41f1-a2b8-7fdfa18e1348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart-page&quot;]/div[2]/div[@class=&quot;cart-product-section-wrapper&quot;]/div[@class=&quot;wrapper-body&quot;]/section[@class=&quot;cart-product-section&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;section-inner&quot;]/div[@class=&quot;section-body&quot;]/div[@class=&quot;product-cart-block&quot;]/div[@class=&quot;main-product-segment&quot;]/div[@class=&quot;segment-right-col&quot;]/div[@class=&quot;segment-right-top-row&quot;]/div[@class=&quot;product-control-col&quot;]/button[@class=&quot;control-btn&quot;]</value>
      <webElementGuid>a2665e07-68af-4f2a-a0cf-aeed4a9a374b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>36b43d1f-6269-4b69-aa45-5c93c7ad7a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Xoá sản phẩm']</value>
      <webElementGuid>373f7246-1aa6-4880-aab5-74c91d8d4c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
