<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_captcha</name>
   <tag></tag>
   <elementGuidId>c8dc372f-5afe-4f1b-9bd7-a2f17066eaf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;captcha&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='captcha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df28616f-8c5e-48e4-97c7-7618602b8730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc0e153d-941f-48c5-808e-12d0b8e1a520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-form-control</value>
      <webElementGuid>c3a300c2-b997-4dc7-aad5-2c337c9eb85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>captcha</value>
      <webElementGuid>5b0b021b-57eb-4e21-9316-fcffcb51298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập mã xác nhận</value>
      <webElementGuid>0b35b5e9-53f2-4aeb-956e-2d413470697c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-block__register-form&quot;)/div[@class=&quot;mz-form-group&quot;]/div[@class=&quot;mz-form-group__control-col&quot;]/div[@class=&quot;mz-flex mz-flex-wrap mz--mx-4&quot;]/div[@class=&quot;mz-min-w-0 mz-w-1/2 mz-px-4&quot;]/div[@class=&quot;mz-form-control mz-form-control-md&quot;]/input[@class=&quot;my-form-control&quot;]</value>
      <webElementGuid>948d8100-6b25-46a2-836b-36bccc6db67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='captcha']</value>
      <webElementGuid>2890a654-48b4-4c02-be38-719d52afec1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-block__register-form']/div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>704cbee0-249f-4382-bdfc-1a9865b5b26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/input</value>
      <webElementGuid>a1143ec6-76ca-4ee5-97c1-a771248dcad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'captcha' and @placeholder = 'Nhập mã xác nhận']</value>
      <webElementGuid>b7489c1e-e8c9-47f0-9239-e728b62860d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
