<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mz-number-control__input</name>
   <tag></tag>
   <elementGuidId>ad6fb516-8674-4f63-834c-af5163a54cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8ac4344-b9c0-49b6-b1b4-0c9401a06212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9b3753fb-98e4-4b25-8e16-bfcf6163e75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mz-number-control__input</value>
      <webElementGuid>7b8fa5a1-a60d-4215-b6b4-a715030515dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart-page&quot;]/div[2]/div[@class=&quot;cart-product-section-wrapper&quot;]/div[@class=&quot;wrapper-body&quot;]/section[@class=&quot;cart-product-section&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;section-inner&quot;]/div[@class=&quot;section-body&quot;]/div[@class=&quot;product-cart-block&quot;]/div[@class=&quot;main-product-segment&quot;]/div[@class=&quot;segment-right-col&quot;]/div[@class=&quot;segment-right-top-row&quot;]/div[@class=&quot;product-quantity-col&quot;]/div[@class=&quot;mz-number-control mz-number-control-md&quot;]/input[@class=&quot;mz-number-control__input&quot;]</value>
      <webElementGuid>f3f784d9-1eec-45ff-818e-2ee0f13884b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[2]</value>
      <webElementGuid>2d3ff28e-45d2-4cae-818c-0a57d321f530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>53e26d3d-5612-4d0f-ae16-8f2138735389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>eebe45fd-db41-46c7-aad2-497f7ad12dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
