<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframemeili</name>
   <tag></tag>
   <elementGuidId>316f30e4-8460-4dce-9072-456650721c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meili</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='meili']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2e0fd791-9a22-4d7b-8ffd-0759bb4f1392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://captcha.tiki.vn/embed/challenges/1cc3c014-065f-4153-8782-fadd5de762b6</value>
      <webElementGuid>1ee9f9bd-39fc-4a7f-bb9f-72e958953c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meili</value>
      <webElementGuid>32ad7407-dc6d-4191-8358-b31a21171cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tiki's Captcha</value>
      <webElementGuid>46a1b675-bc47-40b6-845f-4414f4ba26cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meili&quot;)</value>
      <webElementGuid>0a23d253-fc39-4835-ab76-c802880a31c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='meili']</value>
      <webElementGuid>63459efe-b8d3-4a97-82fd-082a7b78b598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe[4]</value>
      <webElementGuid>ea518a5f-4ff4-4862-bd1a-1e014a5a6431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://captcha.tiki.vn/embed/challenges/1cc3c014-065f-4153-8782-fadd5de762b6' and @id = 'meili' and @title = concat(&quot;Tiki&quot; , &quot;'&quot; , &quot;s Captcha&quot;)]</value>
      <webElementGuid>21b07dd3-5363-449b-976f-be2e512144bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
