<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4fd42ca0-e0ef-4b83-8e9c-d3b7e0affb16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;header_header_account_img&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='main-header']/div/div/div[2]/div/div[2]/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6161ba34-6d8a-4c32-86e8-dcf4c42ee249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://salt.tikicdn.com/ts/upload/07/d5/94/d7b6a3bd7d57d37ef6e437aa0de4821b.png</value>
      <webElementGuid>bf40ca7e-324c-42a1-84c1-6bd2be3a9ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>header_header_account_img</value>
      <webElementGuid>6e9f8884-bca3-441c-9bf1-3f8f2dadb2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-header&quot;)/div[@class=&quot;ContainerRevamp-sc-1hvvgwz-0 dOGdaN&quot;]/div[@class=&quot;HomeRevampHeader__HeaderLayout-sc-1n94l81-1 bflSia&quot;]/div[@class=&quot;HomeRevampHeader__SearchContainerStyled-sc-1n94l81-0 huqeuo&quot;]/div[@class=&quot;Middle__Wrap-sc-vop1h1-0 edlkEo&quot;]/div[@class=&quot;Userstyle__RootRevamp-sc-6e6am-15 hkQlMw&quot;]/div[@class=&quot;Userstyle__MenuItemRevamp-sc-6e6am-19 fUChpf&quot;]/img[1]</value>
      <webElementGuid>f9ae6097-7517-4263-964b-5153e097f542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='main-header']/div/div/div[2]/div/div[2]/div[2]/img</value>
      <webElementGuid>5b042bbb-e882-4d7c-a166-2341558d9a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='header_header_account_img']</value>
      <webElementGuid>8d26a3c2-c4f7-4b26-9555-0bb56f3c1010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>aaf70811-0a3b-454c-b91f-ff36ff603d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://salt.tikicdn.com/ts/upload/07/d5/94/d7b6a3bd7d57d37ef6e437aa0de4821b.png' and @alt = 'header_header_account_img']</value>
      <webElementGuid>d999b24a-ff46-45a2-9a3f-0776e1bbf719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
