<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_styles__InputRevamp-sc-6cbqeh-2 IXqBC</name>
   <tag></tag>
   <elementGuidId>87ebc5c4-f6f9-4207-a247-d3fe6e19c0ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styles__InputRevamp-sc-6cbqeh-2.IXqBC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4967a5a7-ce06-4acb-81f0-e258f461f517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d69bd067-36a5-443f-87e7-8552fb88e01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-id</name>
      <type>Main</type>
      <value>main_search_form_input</value>
      <webElementGuid>ed29113e-7603-427d-9242-73182aa8c733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn tìm gì hôm nay</value>
      <webElementGuid>ccd972bf-5b04-41fc-b5e2-5d50f1a569d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__InputRevamp-sc-6cbqeh-2 IXqBC</value>
      <webElementGuid>321f921f-4aec-406f-b990-71e866bf3ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-header&quot;)/div[@class=&quot;ContainerRevamp-sc-1hvvgwz-0 dOGdaN&quot;]/div[@class=&quot;HomeRevampHeader__HeaderLayout-sc-1n94l81-1 bflSia&quot;]/div[@class=&quot;HomeRevampHeader__SearchContainerStyled-sc-1n94l81-0 huqeuo&quot;]/div[@class=&quot;Middle__Wrap-sc-vop1h1-0 edlkEo&quot;]/div[@class=&quot;Middle__LeftContainer-sc-vop1h1-1 hBRVdJ&quot;]/div[@class=&quot;styles__Root-sc-6cbqeh-0 hULqIV&quot;]/div[@class=&quot;styles__FormRevamp-sc-6cbqeh-1 cTCXTh&quot;]/input[@class=&quot;styles__InputRevamp-sc-6cbqeh-2 IXqBC&quot;]</value>
      <webElementGuid>fe4c9096-e612-46cc-9d49-8855632952be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>529d64ad-d711-4f51-9a64-8d49f2d982c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='main-header']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>a836be1a-2536-4ad0-8197-1dfeb75347ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>275047c4-4b88-4651-857c-9ea1754c5a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Bạn tìm gì hôm nay']</value>
      <webElementGuid>50c41ffa-8b4b-4198-87af-f9aa10693f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
