<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_styles__InputRevamp-sc-6cbqeh-2 IXqBC_1</name>
   <tag></tag>
   <elementGuidId>8ffd4996-c2ba-4102-95e2-935da27c163b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.styles__InputRevamp-sc-6cbqeh-2.IXqBC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='học các']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a50f76b-4bbc-4322-b2c7-84ac477962d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>920761f6-d16e-4f07-98f8-bf4d34000bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-view-id</name>
      <type>Main</type>
      <value>main_search_form_input</value>
      <webElementGuid>6090bb89-6ca3-4a3d-9a36-a22ae775045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>học các</value>
      <webElementGuid>081688a8-d93d-4359-9452-d394e2fe3e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Giao nhanh 2H &amp; đúng khung giờ</value>
      <webElementGuid>2a8bbab0-2a5b-49b6-95f0-5749bac2e0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__InputRevamp-sc-6cbqeh-2 IXqBC</value>
      <webElementGuid>734275fc-3db8-4ef0-b024-a7f9b6ff1528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-header&quot;)/div[@class=&quot;ContainerRevamp-sc-1hvvgwz-0 dOGdaN&quot;]/div[@class=&quot;HomeRevampHeader__HeaderLayout-sc-1n94l81-1 bflSia&quot;]/div[@class=&quot;HomeRevampHeader__SearchContainerStyled-sc-1n94l81-0 huqeuo&quot;]/div[@class=&quot;Middle__Wrap-sc-vop1h1-0 edlkEo&quot;]/div[@class=&quot;Middle__LeftContainer-sc-vop1h1-1 hBRVdJ&quot;]/div[@class=&quot;styles__Root-sc-6cbqeh-0 hULqIV&quot;]/div[@class=&quot;styles__FormRevamp-sc-6cbqeh-1 cTCXTh&quot;]/input[@class=&quot;styles__InputRevamp-sc-6cbqeh-2 IXqBC&quot;]</value>
      <webElementGuid>f9ef1895-3b65-41b1-82f7-2cb9898e963b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='học các']</value>
      <webElementGuid>0438f811-3001-42f4-863f-34c86d3a77a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='main-header']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>38be5cdd-8a67-44d7-a9a8-da2299d30f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d8cfe5d2-d5be-4f58-8bd2-06c288504c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Giao nhanh 2H &amp; đúng khung giờ']</value>
      <webElementGuid>c3104697-755f-4f32-90ec-b614204f0526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
