<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tel</name>
   <tag></tag>
   <elementGuidId>fba2eea1-8cd3-4e44-ba00-c34bfa76fc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37cacf85-48c0-41fb-96d2-992f61a755c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bb822d67-725e-4e95-bb19-f9acac637b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9c3b7bef-6d79-418b-b078-17093ba26872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại</value>
      <webElementGuid>42020842-8151-465d-9155-a21633ba0992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>71e62ceb-e9d9-41bb-af4c-27a9704adb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f45f94eb-40a3-47b7-b3c3-351cf0ab8ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;ReactModal__Body--open&quot;]/div[@class=&quot;ReactModalPortal&quot;]/div[@class=&quot;ReactModal__Overlay ReactModal__Overlay--after-open&quot;]/div[@class=&quot;ReactModal__Content ReactModal__Content--after-open&quot;]/div[@class=&quot;styles__Root-sc-2hr4xa-0 jyAQAr&quot;]/div[@class=&quot;styles__Left-sc-2hr4xa-1 iwneWf&quot;]/div[@class=&quot;styles__StyledLoginWithPhone-sc-si1ros-0 jdahxv&quot;]/form[1]/div[@class=&quot;input input-fill&quot;]/input[1]</value>
      <webElementGuid>2e58873d-1096-4446-b5a8-4988bc3caf4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tel']</value>
      <webElementGuid>05153bc1-7a93-468d-9c69-7d66a1e72dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>92e4d4f1-f6b7-4032-ace3-dfa6c428fe37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'tel' and @placeholder = 'Số điện thoại']</value>
      <webElementGuid>33d8446c-9ace-40ff-a942-940500c3fad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
