<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__mz-number-control__up-btn</name>
   <tag></tag>
   <elementGuidId>adfee31a-951d-49d8-becb-e6f1540c84f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mz-number-control__up-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49efbc90-a9b5-4c8f-bf50-340d5734bd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mz-number-control__up-btn</value>
      <webElementGuid>42773fa3-8fbd-4de4-acc1-7c8951b720dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart-page&quot;]/div[2]/div[@class=&quot;cart-product-section-wrapper&quot;]/div[@class=&quot;wrapper-body&quot;]/section[@class=&quot;cart-product-section&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;section-inner&quot;]/div[@class=&quot;section-body&quot;]/div[@class=&quot;product-cart-block&quot;]/div[@class=&quot;main-product-segment&quot;]/div[@class=&quot;segment-right-col&quot;]/div[@class=&quot;segment-right-top-row&quot;]/div[@class=&quot;product-quantity-col&quot;]/div[@class=&quot;mz-number-control mz-number-control-md&quot;]/div[@class=&quot;mz-number-control__btn-wrap&quot;]/button[@class=&quot;mz-number-control__up-btn&quot;]</value>
      <webElementGuid>d7c99d42-ed20-4d5b-832e-9862943ba371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8a7a94ee-c5f2-4250-bb00-91d3352deb4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
