<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ng nhp</name>
   <tag></tag>
   <elementGuidId>d90912d9-36b8-461c-a0ec-cf1dc7a96a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.section-body__item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf6d69e5-7e7c-41c4-9d81-01bd7593c799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-body__item-text</value>
      <webElementGuid>c742fa2d-97da-498d-8d2b-aeb8dee23768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Đăng nhập
              </value>
      <webElementGuid>bd72dab0-e039-4d2c-bda3-a850e3b4eec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__user-col&quot;]/a[@class=&quot;section-body__item&quot;]/div[@class=&quot;section-body__item-text&quot;]</value>
      <webElementGuid>62cddc8e-42ec-4e15-868d-6344467ffef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      <webElementGuid>0a1779f1-c813-43b1-9d81-eb274eb8a780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>68b87ee4-465f-48e2-b0cf-7b7b0287f6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Đăng nhập
              ' or . = '
                Đăng nhập
              ')]</value>
      <webElementGuid>c5b409ff-7155-4f4c-9b15-8ee7a03bf52d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
