<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_close-pop-btn</name>
   <tag></tag>
   <elementGuidId>6291dd34-1a10-482d-bd11-a2492609de3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='chat-panel']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.chat-pop > div.close-pop-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a616d8b2-1e28-422c-b30f-7ba214a2a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-pop-btn</value>
      <webElementGuid>c40e829d-9d45-4167-a4f7-34d522a07771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-panel&quot;)/div[@class=&quot;chat-pop&quot;]/div[@class=&quot;close-pop-btn&quot;]</value>
      <webElementGuid>f1fca6ef-fae1-4077-b48a-ded39f527030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chat-panel']/div[3]/div</value>
      <webElementGuid>ba134248-7dfc-4956-ac9f-965b085138d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div[3]/div</value>
      <webElementGuid>c7f4e0f6-d531-4232-8ec1-8335299225b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
