<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Classic F91W Series Quartz Watch  Water_340624</name>
   <tag></tag>
   <elementGuidId>fc451511-104b-4011-8f3a-fb355afba2e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-cart-success-modal-product-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-cart-success-modal-product-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a55dfbc7-3301-484b-b77a-e86a843fcc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-cart-success-modal-product-name</value>
      <webElementGuid>3845ccaf-3a76-4e97-9d20-20e923b1b5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-cart-success-modal-product-name is-show</value>
      <webElementGuid>cda2b852-13b7-4752-b128-8bc9fb41e975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classic F91W Series Quartz Watch | Water Resistant |1/100 Second Stopwatch | Daily Alarm | Hourly Time Signal |Auto Calendar |SS Caseback |12/24-Hour Format</value>
      <webElementGuid>916f5487-553c-417f-907f-d0126b1e1f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-cart-success-modal-product-name&quot;)</value>
      <webElementGuid>e48be470-3609-4a80-b4da-d1b12ecddfb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='add-cart-success-modal-product-name']</value>
      <webElementGuid>b0fae9b4-73c2-4065-90e0-05619a74eef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-cart-success-modal']/div/div/div[2]</value>
      <webElementGuid>c6274e3b-01c8-4084-936e-44bbf4dcd885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]</value>
      <webElementGuid>53435ea9-4aa8-44df-8893-17b70dccfd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'add-cart-success-modal-product-name' and (text() = 'Classic F91W Series Quartz Watch | Water Resistant |1/100 Second Stopwatch | Daily Alarm | Hourly Time Signal |Auto Calendar |SS Caseback |12/24-Hour Format' or . = 'Classic F91W Series Quartz Watch | Water Resistant |1/100 Second Stopwatch | Daily Alarm | Hourly Time Signal |Auto Calendar |SS Caseback |12/24-Hour Format')]</value>
      <webElementGuid>fef2b2f9-b7c9-4284-b789-12f43548b4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
