<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>53f363a1-586d-411b-bbcf-99688963a7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-block__form-group__email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-block__form-group__email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>491bfbe9-f151-4386-8689-bc16fde6ba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0102dea2-10e5-4b26-bbca-9d8016a7ac6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-block__form-group__email</value>
      <webElementGuid>39c87542-c1c4-4f7f-a140-894db7c5c986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-form-control</value>
      <webElementGuid>01b09a75-a458-42f5-a1f8-19a3f9a88dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7c6f102d-0e9b-4f29-a674-f21fb7f497a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attributename</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8a322a0e-41dc-4721-8645-a11adbaa39f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email của quý khách</value>
      <webElementGuid>b225f47b-ca28-48f4-bc67-1152913ce960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-block__form-group__email&quot;)</value>
      <webElementGuid>57c59f5d-b8be-4000-9a4c-82c09d85b971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-block__form-group__email']</value>
      <webElementGuid>33ebbec2-9f7d-4dbe-a945-c4fec9bd8ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-block__login-form']/div/div[2]/div/input</value>
      <webElementGuid>efdd7045-aa2a-47e7-9a8a-2f04a3c47455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>032d894d-0ee1-42a1-9a95-26c8452ab272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'auth-block__form-group__email' and @name = 'email' and @placeholder = 'Địa chỉ email của quý khách']</value>
      <webElementGuid>7fc6af63-0d53-4a4f-b289-f50d5898bc14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
