<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>3587d408-079d-43ae-b85c-8f8b583cb513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-block__register-form__password-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#auth-block__register-form__password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0e096b7-af92-4aa9-af04-595e8b160cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-block__register-form__password-input</value>
      <webElementGuid>8dd66531-ac4a-412f-8c34-2de3ee8ef6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4951dc78-c289-4cf8-a253-d59f9278f887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-form-control</value>
      <webElementGuid>3d0c50bd-1bb7-4f67-b534-224b669b5229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>04e8849d-85ed-4dcf-8328-4b793c886dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu của quý khách</value>
      <webElementGuid>e5e4ee37-f90a-48cd-a039-e132e8d160ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-block__register-form__password-input&quot;)</value>
      <webElementGuid>1ef6a2cd-bab4-42b4-ab07-a958a47c8f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-block__register-form__password-input']</value>
      <webElementGuid>2a37ad35-36aa-4477-8db1-ee384e8753ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-block__register-form']/div[4]/div[2]/div/div/div/input</value>
      <webElementGuid>8eaa17db-e027-48d0-b661-256fa873a2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>9d01a3fd-87f3-4f50-90ab-170014de825f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auth-block__register-form__password-input' and @type = 'password' and @name = 'password' and @placeholder = 'Mật khẩu của quý khách']</value>
      <webElementGuid>44b3a25f-3203-40c9-a58a-763bba4779ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
