<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ng nhp</name>
   <tag></tag>
   <elementGuidId>80a92d2d-b2e0-491e-a78c-47e10aeb7fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.section-body__item-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>464e4572-a6e9-44e2-9311-a801549d60a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-body__item-text</value>
      <webElementGuid>bd3751c8-c3eb-4baa-9181-3c634555d133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Đăng nhập
              </value>
      <webElementGuid>3e1d6242-1d42-43ee-8496-f3c9010768f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;section-body&quot;]/div[@class=&quot;header-main-block&quot;]/div[@class=&quot;mz-container&quot;]/div[@class=&quot;header-main-block__user-col&quot;]/a[@class=&quot;section-body__item&quot;]/div[@class=&quot;section-body__item-text&quot;]</value>
      <webElementGuid>49a2bff3-ef2f-4151-8b71-28c674275a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='header-section']/div[2]/div/div/div[3]/a/div[2]</value>
      <webElementGuid>391ec871-ce35-432f-93ac-8188a3f5f09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>91171cf8-6d4a-422b-9710-72b7094ce440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                Đăng nhập
              ' or . = '
                Đăng nhập
              ')]</value>
      <webElementGuid>e2ee708f-2356-4d69-a3fb-0610642a41d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
